### ISSUE TITLE
msvcrt.lib(loadcfg.obj) : error LNK2001: unresolved external symbol __enclave_config

### ISSUE THREAD

**Issue by myshiop** [NVlabs/nvdiffmodeling#1]
hi, Thanks for your project. When I try to run sphere to cow demo, I will report this error:
msvcrt.lib(loadcfg.obj) : error LNK2001: unresolved external symbol __enclave_config
renderutils_plugin.pyd : fatal error LNK1120: Unresolved external command
ninja: build stopped: subcommand failed.

Is it because of my Nanjia version?  my current version is: 
nanjia:1.10.2
pytorch:1.8.1
torchvision:0.9.1
cudnn:7.6.5
cuda:10.2

**Comment by jmunkberg** [comment]
Can you provide more details? I just tested with the latest version of Python and PyTorch, and Visual Studio compiler version 14.28.29910 (I have Visual Studio 2019, v 16.9.4 installed), and could not reproduce the issue. I think it is an issue with the Visual Studio version, or perhaps a missing Windows SDK.

nvdiffmodeling installed using 
```
conda create -n debug python=3.8
conda install pytorch torchvision torchaudio cudatoolkit=11.1 -c pytorch -c conda-forge
conda install imageio
pip install PyOpenGL glfw
```
then nvdiffrast installed in the `debug` env

ninja                     1.10.2
pytorch                   1.8.1           py3.8_cuda11.1_cudnn8_0

**Comment by myshiop** [comment]
@jmunkberg thank you，i had tried to follow your steps, i also reported this error. I'll try installing vs2019 again
