### ISSUE TITLE
using camera calibration matrices

### ISSUE THREAD

**Issue by maorp** [NVlabs/nvdiffmodeling#10]
Hi, first thanks for sharing this work! I'm trying to solve inverse rendering problem using a photogrammetry dataset which comes with accurate camera calibration mats. i have started from the spot example and i need to convert my intrinsic\extrinsic params to be used in the rastering and cant find an example or a guide to do it. the only hint is that I know it should be converted to openGL and NDC according to nvdiffrast, ill be happy to get an advice, thanks.

**Comment by jmunkberg** [comment]
Thanks!
We don't have an example in the released code, but it is straightforward to convert from the coordinate systems used by e.g., OpenCV into OpenGL coordinates, which is used by nvdiffrast. 
Please refer to the nvdiffrast documentation w.r.t. coordinate systems & conventions (OpenGL)
https://nvlabs.github.io/nvdiffrast/#coordinate-systems
