### ISSUE TITLE
Input meshes

### ISSUE THREAD

**Issue by jiaxiangshang** [NVlabs/nvdiffmodeling#14]
Excellent work, but can you give the examples meshes for ref and base.

Thanks

**Comment by jmunkberg** [comment]
Thanks, 
What meshes do you want? As noted in the readme, the assets are available here: https://github.com/NVlabs/nvdiffmodeling/releases/download/v1.0/assets.zip
including the reference meshes.

The configs *_paper.json should reproduce the results in the paper.

**Comment by jiaxiangshang** [comment]
Oh, I am sorry, I got it now.
Thanks you very much
