### ISSUE TITLE
How to improve the optimization effect

### ISSUE THREAD

**Issue by Lucklycat** [NVlabs/nvdiffmodeling#18]
Your work is great. Thank you very much for your openness. I tried to use rendering on my own model, but I encountered the following problems and would like to consult:
1.In the process of rendering, I found that the face of the character, especially the eyes, was not poorly optimized, and the color could not be reflected. Are there any parameters that need to be adjusted?
![image](https://user-images.githubusercontent.com/17697877/207837859-f27ee707-2f75-4733-9715-62a2ab074546.png)
2.During rendering, I encountered that. mtl contains a map_ The texture of d cannot be represented in the renderer. How can I solve this problem?
![image](https://user-images.githubusercontent.com/17697877/207838427-69f63ec7-c45d-4a62-9c51-8dfdae0dff8e.png)

Thank you for your reply

**Comment by jmunkberg** [comment]
Please refer to the configs in the repo. This is a good starting point https://github.com/NVlabs/nvdiffmodeling/blob/main/configs/spot.json

You can test to increase the batch size, training and texture resolution (if you have enough GPU memory) for higher quality results. As discussed in the paper, the quality also depends on the geometry and texture parametrization of the base mesh.

**Comment by Lucklycat** [comment]
Thank you for your reply，i will to try
