### ISSUE TITLE
Texture maps have a lot of noise

### ISSUE THREAD

**Issue by Lucklycat** [NVlabs/nvdiffmodeling#19]
Thank you very much for your work！
When I tried the ewer example, I found the following textures：
![image](https://user-images.githubusercontent.com/17697877/209643556-02d6a0d0-3f71-40a5-98a8-630c6aecc428.png)
When you zoom in, you will find many red, yellow and green noises
![image](https://user-images.githubusercontent.com/17697877/209643636-560546c5-b0c3-403c-b08a-4d517bfda71a.png)
This is still the case when I import the output obj into blender, but the contrast image rendered from nvdiffast does not show this situation. What is the reason?
![image](https://user-images.githubusercontent.com/17697877/209643828-314b86e7-d57f-4a02-818c-69ecc3ad1782.png)

**Comment by jmunkberg** [comment]
Note that we optimize the full mip hierarchy for each texture, so depending on the rendering and texture resolutions, the highest resolution mip levels may not be fully used (and in that case, noise will remain, as no gradients flows to those texels). You can e.g., test to reduce the texture resolution, which may decrease texture detail but also reduce the noise levels in the higher resolution mip level.

For a match in other renderers (e.g., Blender), you must ensure that the same texture filtering algorithm is applied.

**Comment by Lucklycat** [comment]
thanks
