### ISSUE TITLE
Unreal Engine Paragon asset  settings   .json

### ISSUE THREAD

**Issue by TLJParadox** [NVlabs/nvdiffmodeling#2]
could you tell me something about  _Automatic cleanup._   in figure 7  this paper.  What's your  param settings(json)  in Unreal Engine Paragon asset.

**Comment by jmunkberg** [comment]
Hello, 
In that experiment, we first reduced the model from 81k tris to 15k tris using the mesh reduction tool in Maya 2019, and used the reduced model as initial guess. The relevant parameters in the .json files are:
```
    "texture_res" : [1024, 8192],
    "train_res" : 2048,
    "batch": 8,
    "learning_rate" : 0.003,
    "iter" : 5000,
```

**Comment by TLJParadox** [comment]
- Thank you. How about `"random_textures": true,"min_roughness" : 0.25` ?  
- And how to calculate the diffuse map , such as in dancer_displacement  `"mtl_override": "data/dancer/dancer_diffuse.mtl"` ?
- dancer_1k.obj and dancer_8k.obj are also generated by Maya 2019? I use the Unreal4 to LOD in Paragon asset, but the experiment result isn't better than base_mesh what we got.

**Comment by jmunkberg** [comment]
`"random_textures" : false,`  and no `mtl_override` so the optimization will use the textures from the reduced initial guess as a starting point.

`min_roughness` is not set in the json file, so will get the default value of 0.08

IIRC, the dancer models were generated in Simplygon as that produced better approximations than Maya. 
We haven't tested Unreal to generate LODs so cannot comment on the quality there.
