### ISSUE TITLE
about effect  Fig.22 and Fig 23

### ISSUE THREAD

**Issue by Lucklycat** [NVlabs/nvdiffmodeling#20]
I read your paper and video in detail，about LEARNING MESH AND MATERIALS FROM IMPLICIT SURFACES,How to improve the effect？
Can you give me some suggestions on setting super parameters?
I used my own model as the target, started from the sphere you provided, and carried out experiments. I found that the feet and face were always unsatisfactory?
There is a big gap with the rendering of snails and elephants mentioned in your paper.
can you give me some adivce.
![image](https://user-images.githubusercontent.com/17697877/209915438-7aa87576-cef4-41f8-b1a0-df8c372beff9.png)

**Comment by jmunkberg** [comment]
Hello, 

Deforming a sphere to a character (or elephant) is quite challenging. For those examples in the paper, we used 
a sphere with 12k triangles (higher tessellation than the sphere provided in the code repo) as an initial guess for the rasterizer, and optimized at a resolution of 2048 × 2048 pixels for 10k steps. You can tweak the Laplacian regularizer weight to steer the optimization process a bit (e.g., to better capture smaller features). 

That said, you would likely obtain better results with a better initial guess that a sphere, or by switching to nvdiffrec, which handles this case without the need for an initial mesh. https://github.com/NVlabs/nvdiffrec

**Comment by Lucklycat** [comment]
Thanks for your reply, I'll try
