### ISSUE TITLE
What software is the result of the paper displayed in

### ISSUE THREAD

**Issue by Lucklycat** [NVlabs/nvdiffmodeling#27]
Thank you very much for your work.
In the original paper, Fig6, Fig7, and Fig9 are equal to each other. You should import your output mesh into some software before you can compare it,
Please tell me what software you use

**Comment by jmunkberg** [comment]
We used the path tracer in NVIDIA's Falcor framework: https://developer.nvidia.com/falcor to render Fig 7. 
Fig 6 and Fig 8 are rendered directly in nvdiffmodeling
