### ISSUE TITLE
Is it possible to run the code on Linux?

### ISSUE THREAD

**Issue by X1aoyueyue** [NVlabs/nvdiffmodeling#30]
Hello, I want to run the code on Supercomputer and do some parallel rendering. I woule like to know if it is ok to run on a Linux os. And will it possible work for my idea? I want to let one GPU to optimize the base mesh and let other GPUs to render the ref mesh. I think this way will help to load big mesh data.

Thanks.

**Comment by jmunkberg** [comment]
Yes, linux should work out of the box. We included docker instructions in the readme: https://github.com/NVlabs/nvdiffmodeling#server-usage-through-docker

For multiGPU, we did not add support in this project, but a later, very similar code base does have mGPU support:
https://github.com/NVlabs/nvdiffrec#examples so hopefully you can adapt a similar strategy (we used [PyTorch DDP](https://pytorch.org/docs/stable/elastic/run.html#launcher-api)

Also see my reply at https://github.com/NVlabs/nvdiffmodeling/issues/16

**Comment by X1aoyueyue** [comment]
Thanks a lot. I will try.
