### ISSUE TITLE
About the raymarch fitting case

### ISSUE THREAD

**Issue by outlawever** [NVlabs/nvdiffmodeling#9]
Thanks for the marvelous work! I have some questions related to the shadertoy fitting case:
It seems figure 22 & figure 23 use some special uv un-wrap methods, can you elaborate the algorithm under the hood?
![image](https://user-images.githubusercontent.com/32186058/138996117-8dd91080-4ee6-4e68-8ecf-cb5126253de1.png)

**Comment by FishWoWater** [comment]
> Exactly. We don't optimize topology, nor the UV params, but assume a base mesh with fixed topology (genus 0 in this case), and non-overlapping UVs. You can find additional examples of the base meshes and corresponding UVs we use in the additional assets (link the the readme).

Hi, Munkberg
I have noticed that at the end of Section3 in your paper, you mentioned that the initial mesh is required to have non-overlapping texture parameterization.  Why is it necessary to have non-overlapping UVs?  Just intuitively, nvdiffmodeling should also work with  models whose UVs reuse the same texture region

**Comment by JHnvidia** [comment]
Hi @FishWoWater,

There's no strict requirement for unique UV mapping. However, multiple pixels/parts of an object mapping to the same texel, optimization will converge towards the average. It's fine as long as there's no ambiguity, but if overlapping regions have different materials you will get a blurred/washed out loook. E.g. if a texture region maps to both a white and black square on a checkerboard, you would get an average gray.

It's recommended to use uv-unwrapping, but some special cases such as mirrored mapping on a character might work well with non-unique mapping.

**Comment by FishWoWater** [comment]
@JHnvidia Got it, thank you so much :)
